name: update-state
run-name: Aktualizace stavu
on:
    schedule:
    - cron: '40 0,8,16 * * *'
permissions:
    contents: write
jobs:
    update-state:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repozitáře
              uses: actions/checkout@v3
            - name: Spustit aktualizační skript
              shell: bash
              env:
                IGSESSIONID: ${{ secrets.IGSESSIONID }}
              run: ./update.sh
