name: update-state
run-name: Aktualizace stavu
on:
    schedule:
    - cron: '40 8,16,19 * * *'
    workflow_dispatch:
permissions:
    contents: write
jobs:
    update-state:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repozitáře
              uses: actions/checkout@v3
            - name: Spustit aktualizační skript
              env:
                IGSESSIONID: ${{ secrets.IGSESSIONID }}
                IGUSERID: ${{ vars.IGUSERID }}
                GH_USERNAME: ${{ github.actor }}
              run: ./update.sh
